[package]
name = "bluetooth_icce_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bluer = { version = "0.15.7", features = ["full"] }
futures = "0.3.28"
lazy_static = "1.4.0"
tokio = { version = "1.29.1", features = ["full"] }
uuid = "1.4.1"
